default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: project_pixel_react_development

test:
  <<: *default
  database: project_pixel_react_test

production:
  <<: *default
  database: project_pixel_react_production
  username: project_pixel_react
  password: <%= ENV['PROJECT_PIXEL_REACT_DATABASE_PASSWORD'] %>
